/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subMenu;

import com.mysql.cj.jdbc.Driver;
import java.awt.Color;
import java.sql.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.Connect;
/**
 *
 * @author perlengkapan
 */
public class LaporanFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LaporanFrame
     */
    public LaporanFrame() {
        initComponents();
        tampilkandata();
        
        //hilangin border 
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);
        
        msg_tblKosong.setForeground(Color.white);
        
        long waktu = System.currentTimeMillis();
        Date today = new Date(waktu);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        int tahunNow = Integer.parseInt(sdf.format(today));
        pilihTahun.setEndYear(tahunNow);
    }
    
    public void tampilkandata(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Penyewa");
        model.addColumn("Nama Karyawan");
        model.addColumn("Tanggal Input");
        model.addColumn("Total");

        try {
            int no=1;
            String sql = "SELECT * FROM laporan JOIN data_sewaan ON laporan.id_sewaan = data_sewaan.id_sewaan\n" +
                         "JOIN pengguna ON pengguna.id_pengguna = laporan.id_pengguna";
            Connection conn = (Connection)Connect.GetConnection();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                    model.addRow(new Object[] {no++,res.getString("id_sewaan"),
                    res.getString("nama_pengguna"),res.getString("tanggal_transaksi"),res.getString("total")});
            }
            
            jTable1.setModel(model);
        } catch (Exception e){

      }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pilihTahun = new com.toedter.calendar.JYearChooser();
        jfilterbulan = new javax.swing.JComboBox<>();
        btn_cari = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpenyewa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        msg_tblKosong = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proses"));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jfilterbulan.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jfilterbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        btn_cari.setBackground(new java.awt.Color(66, 139, 202));
        btn_cari.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btn_cari.setForeground(new java.awt.Color(255, 255, 255));
        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/cari.png"))); // NOI18N
        btn_cari.setText("Cari");
        btn_cari.setBorder(null);
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(92, 184, 92));
        btn_refresh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/reload.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.setBorder(null);
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refreshMouseClicked(evt);
            }
        });

        btn_cetak.setBackground(new java.awt.Color(91, 192, 222));
        btn_cetak.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/cetak.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.setBorder(null);
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bulan");

        jLabel2.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tahun");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jfilterbulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pilihTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfilterbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 890, 200));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Nama Penyewa", "Nama Karyawan", "Tanggal Transaksi", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 890, 210));

        jpenyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpenyewaKeyReleased(evt);
            }
        });
        getContentPane().add(jpenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cari");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, 30));

        msg_tblKosong.setFont(new java.awt.Font("Outfit", 0, 12)); // NOI18N
        msg_tblKosong.setForeground(new java.awt.Color(255, 255, 255));
        msg_tblKosong.setText("Data yang anda cari kosong / tidak ada");
        getContentPane().add(msg_tblKosong, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 230, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/background.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        try {
            int year = pilihTahun.getYear();
            int bulan = jfilterbulan.getSelectedIndex()+1;
            
            String sqlCari = "SELECT * FROM laporan WHERE month(tanggal_transaksi)="+bulan+" and year(tanggal_transaksi)="+year+"";

            Connection conn = koneksi.Connect.GetConnection();
            PreparedStatement stm = conn.prepareStatement(sqlCari);
            ResultSet res = stm.executeQuery();
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("No");
            dtm.addColumn("Id Penyewa");
            dtm.addColumn("Nama Karyawan");
            dtm.addColumn("Tanggal Input");
            dtm.addColumn("Total");
            jTable1.setModel(dtm);

            int no = 1;
            while(res.next()){
                dtm.addRow(new Object[]{
                    no++,
                    res.getString("id_sewaan"),
                    res.getString("id_pengguna"),
                    res.getString("tanggal_transaksi"),
                    res.getString("total"),
                });
            }
        }catch (Exception e){

        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        tampilkandata();
    }//GEN-LAST:event_btn_refreshMouseClicked

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        MessageFormat header = new MessageFormat("Print");
        MessageFormat footer = new MessageFormat("");

        try{
            jTable1.print(JTable.PrintMode.NORMAL , header, footer);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel tbl = jTable1.getModel();

        String field1 = tbl.getValueAt(i, 1).toString();
        String field2 = tbl.getValueAt(i, 2).toString();
        String field3 = tbl.getValueAt(i, 3).toString();
        String field4 = tbl.getValueAt(i, 4).toString();
        String field5 = tbl.getValueAt(i, 5).toString();
        String field6 = tbl.getValueAt(i, 6).toString();

        try{
            String sql = "SELECT * FROM laporan WHERE laporan ='"+field1+"'";
            Connection conn = koneksi.Connect.GetConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
        } catch(Exception e){

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jpenyewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpenyewaKeyReleased
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("id_sewaan");
        dtm.addColumn("id_laporan");
        dtm.addColumn("tanggal_input");
        dtm.addColumn("total");
        jTable1.setModel(dtm);

        try {
            Statement statement = (Statement)Connect.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from laporan where id_sewaan like '%"+ jTable1 +"%'");

            while(res.next()){
                dtm.addRow(new Object[]{
                    res.getString("id_sewaan"),
                    res.getString("id_laporan"),
                    res.getString("tanggal_input"),
                    res.getString("total"),
                });
                jTable1.setModel(dtm);

            }
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jpenyewaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jfilterbulan;
    private javax.swing.JTextField jpenyewa;
    private javax.swing.JLabel msg_tblKosong;
    private com.toedter.calendar.JYearChooser pilihTahun;
    // End of variables declaration//GEN-END:variables
}
