/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subMenu;

import subMenu.popUp.DetailTransaksi;
import com.mysql.cj.jdbc.Driver;
import java.awt.Dimension;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.Connect;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author perlengkapan
 */
public class SewaanFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SewaanFrame
     */
    public SewaanFrame() {
        initComponents();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);

        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_carisewaan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sewaan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        btn_detail = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_carisewaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_carisewaanKeyReleased(evt);
            }
        });
        getContentPane().add(txt_carisewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 190, 30));

        tbl_sewaan.setAutoCreateRowSorter(true);
        tbl_sewaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_sewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_sewaan.setRowHeight(30);
        jScrollPane2.setViewportView(tbl_sewaan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 960, 230));

        jLabel5.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel5.setText("Cari");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 30));

        btn_cetak.setBackground(new java.awt.Color(252, 191, 73));
        btn_cetak.setFont(new java.awt.Font("Outfit Medium", 0, 14)); // NOI18N
        btn_cetak.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/printer.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.setBorder(null);
        btn_cetak.setBorderPainted(false);
        btn_cetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cetak.setFocusPainted(false);
        btn_cetak.setIconTextGap(20);
        btn_cetak.setRequestFocusEnabled(false);
        btn_cetak.setVerifyInputWhenFocusTarget(false);
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 40));

        btn_detail.setBackground(new java.awt.Color(252, 191, 73));
        btn_detail.setFont(new java.awt.Font("Outfit Medium", 0, 14)); // NOI18N
        btn_detail.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail.setText("Detail Transaksi");
        btn_detail.setBorder(null);
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        getContentPane().add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 140, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/background.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTable() {
        DefaultTableModel tableModel = new DefaultTableModel() {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tableModel.addColumn("No");
        tableModel.addColumn("Id Sewaan");
        tableModel.addColumn("Nama Penyewa");
        tableModel.addColumn("Jumlah Barang");
        tableModel.addColumn("Tanggal Pinjam");
        tableModel.addColumn("Tanggal Kembali");
        tableModel.addColumn("Total");
        tableModel.addColumn("Status");

        try {
            String sql = "SELECT data_sewaan.id_sewaan, data_sewaan.nama_penyewa, COUNT(detail_data_sewaan.id_barang) AS jumlah_barang ,"
                    + "data_sewaan.tgl_pinjam, data_sewaan.tgl_kembali, data_sewaan.total, STATUS "
                    + "FROM data_sewaan JOIN detail_data_sewaan ON data_sewaan.id_sewaan = detail_data_sewaan.id_sewaan "
                    + "GROUP BY id_sewaan";

            Connection connect = koneksi.Connect.GetConnection();
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            int no = 1;
            while (rs.next()) {
                
                tableModel.addRow(new Object[]{no++, rs.getString("id_sewaan"), rs.getString("nama_penyewa"),
                    rs.getString("jumlah_barang"), rs.getString("tgl_pinjam"), rs.getString("tgl_kembali"), rs.getString("total"),
                    rs.getString("status")});
            }
            tbl_sewaan.setModel(tableModel);
        } catch (Exception e) {

        }
    }

    private void txt_carisewaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_carisewaanKeyReleased
        // TODO add your handling code here:
        String cari = txt_carisewaan.getText();

        DefaultTableModel dtm = new DefaultTableModel() {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        dtm.addColumn("No");
        dtm.addColumn("Id Sewaan");
        dtm.addColumn("Nama Penyewa");
        dtm.addColumn("Jumlah Barang");
        dtm.addColumn("Tanggal Pinjam");
        dtm.addColumn("Tanggal Kembali");
        dtm.addColumn("Total");
        dtm.addColumn("Status");
        tbl_sewaan.setModel(dtm);

        try {
            Statement statement = (Statement) Connect.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT data_sewaan.id_sewaan, data_sewaan.nama_penyewa, "
                    + "COUNT(detail_data_sewaan.id_barang) AS jumlah_barang ,data_sewaan.tgl_pinjam, "
                    + "data_sewaan.tgl_kembali, data_sewaan.total, STATUS FROM data_sewaan JOIN detail_data_sewaan "
                    + "ON data_sewaan.id_sewaan = detail_data_sewaan.id_sewaan "
                    + "WHERE data_sewaan.nama_penyewa LIKE '%" + txt_carisewaan.getText() + "%' GROUP BY id_sewaan");

            while (res.next()) {
                int jumlahrow = tbl_sewaan.getModel().getRowCount();
                dtm.addRow(new Object[]{
                    jumlahrow++,
                    res.getString("id_sewaan"),
                    res.getString("nama_penyewa"),
                    res.getString("jumlah_barang"),
                    res.getString("tgl_pinjam"),
                    res.getString("tgl_kembali"),
                    res.getString("total"),
                    res.getString("status"),});
                tbl_sewaan.setModel(dtm);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txt_carisewaanKeyReleased

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked

    }//GEN-LAST:event_jPanel6MouseClicked

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:
        if(tbl_sewaan.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan pilih data pada table terlebih dahulu");
        }else{
            int i = tbl_sewaan.getSelectedRow();
            String idSewaan = tbl_sewaan.getValueAt(i, 1).toString();

            DetailTransaksi dt = new DetailTransaksi();
            dt.getKodeSewaan(idSewaan);
            dt.setVisible(true);
        }
    }//GEN-LAST:event_btn_detailActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        //ambil id sewaan dari table
        if(tbl_sewaan.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan pilih data pada table terlebih dahulu");
        }else{
            int i = tbl_sewaan.getSelectedRow();
            String idSewaan = tbl_sewaan.getValueAt(i, 1).toString();

            try{
                Connection conn = koneksi.Connect.GetConnection();
                Statement stm = conn.createStatement();

                String report = ("C:\\Users\\perlengkapan\\Documents\\KULIAH\\Project Tugas Akhir\\Awan-adventure-FIX\\src\\subMenu\\nota\\notaSewaan.jrxml");
                HashMap hash = new HashMap();
                hash.put("id_sewaan", idSewaan);
                JasperReport jasper = JasperCompileManager.compileReport(report);
                JasperPrint jasperP = JasperFillManager.fillReport(jasper, hash, conn);
                JasperViewer.viewReport(jasperP, false);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error iReport");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_cetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_detail;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_sewaan;
    private javax.swing.JTextField txt_carisewaan;
    // End of variables declaration//GEN-END:variables
}
