/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainMenu;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import subMenu.*;

/**
 *
 * @author perlengkapan
 */
public class MenuUtama extends javax.swing.JFrame {
    
    Color colorHover = new Color(252,191,73);
    Color exitHover = new Color(248,221,113);
    
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        btn_beranda.setBackground(colorHover);
        Beranda.setBackground(colorHover);
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);
        infoMenu.setText("Beranda");
        infoSubmenu.setText("Home / Dashboard");
    }
    
    public void setAkun(String akses, String namapengguna, String idpengguna){
        txt_akses.setText(akses);
        txt_namaUser.setText(namapengguna);
        tempat_idPengguna.setText(idpengguna);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JPanel();
        Beranda = new javax.swing.JPanel();
        iconBeranda = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JButton();
        Kasir = new javax.swing.JPanel();
        iconKasir = new javax.swing.JLabel();
        btn_kasir = new javax.swing.JButton();
        Sewaan = new javax.swing.JPanel();
        iconSewaan = new javax.swing.JLabel();
        btn_sewaan = new javax.swing.JButton();
        Barang = new javax.swing.JPanel();
        iconBarang = new javax.swing.JLabel();
        btn_barang = new javax.swing.JButton();
        Pengembalian = new javax.swing.JPanel();
        iconPengembalian = new javax.swing.JLabel();
        btn_pengembalian = new javax.swing.JButton();
        Pengguna = new javax.swing.JPanel();
        iconPengguna = new javax.swing.JLabel();
        btn_pengguna = new javax.swing.JButton();
        Laporan = new javax.swing.JPanel();
        iconLaporan = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JButton();
        icon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        infoMenu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        infoSubmenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_akses = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txt_namaUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        tempat_idPengguna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 675));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menubar.setBackground(new java.awt.Color(248, 221, 113));

        Beranda.setBackground(new java.awt.Color(248, 221, 113));
        Beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BerandaMouseClicked(evt);
            }
        });
        Beranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/home.png"))); // NOI18N
        Beranda.add(iconBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_beranda.setBackground(new java.awt.Color(248, 221, 113));
        btn_beranda.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_beranda.setForeground(new java.awt.Color(0, 0, 0));
        btn_beranda.setText("Beranda");
        btn_beranda.setBorder(null);
        btn_beranda.setBorderPainted(false);
        btn_beranda.setContentAreaFilled(false);
        btn_beranda.setFocusPainted(false);
        btn_beranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_berandaMouseClicked(evt);
            }
        });
        Beranda.add(btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -1, 130, 50));

        Kasir.setBackground(new java.awt.Color(248, 221, 113));
        Kasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KasirMouseClicked(evt);
            }
        });
        Kasir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/kasir.png"))); // NOI18N
        Kasir.add(iconKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_kasir.setBackground(new java.awt.Color(248, 221, 113));
        btn_kasir.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_kasir.setForeground(new java.awt.Color(0, 0, 0));
        btn_kasir.setText("Kasir");
        btn_kasir.setBorder(null);
        btn_kasir.setBorderPainted(false);
        btn_kasir.setContentAreaFilled(false);
        btn_kasir.setFocusPainted(false);
        btn_kasir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kasirMouseClicked(evt);
            }
        });
        Kasir.add(btn_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        Sewaan.setBackground(new java.awt.Color(248, 221, 113));
        Sewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SewaanMouseClicked(evt);
            }
        });
        Sewaan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconSewaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/sewaan.png"))); // NOI18N
        Sewaan.add(iconSewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_sewaan.setBackground(new java.awt.Color(248, 221, 113));
        btn_sewaan.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_sewaan.setForeground(new java.awt.Color(0, 0, 0));
        btn_sewaan.setText("Data Sewaan");
        btn_sewaan.setBorder(null);
        btn_sewaan.setBorderPainted(false);
        btn_sewaan.setContentAreaFilled(false);
        btn_sewaan.setFocusPainted(false);
        btn_sewaan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sewaanMouseClicked(evt);
            }
        });
        Sewaan.add(btn_sewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        Barang.setBackground(new java.awt.Color(248, 221, 113));
        Barang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangMouseClicked(evt);
            }
        });
        Barang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/barang.png"))); // NOI18N
        Barang.add(iconBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_barang.setBackground(new java.awt.Color(248, 221, 113));
        btn_barang.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_barang.setForeground(new java.awt.Color(0, 0, 0));
        btn_barang.setText("Data Barang");
        btn_barang.setBorder(null);
        btn_barang.setBorderPainted(false);
        btn_barang.setContentAreaFilled(false);
        btn_barang.setFocusPainted(false);
        btn_barang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangMouseClicked(evt);
            }
        });
        Barang.add(btn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        Pengembalian.setBackground(new java.awt.Color(248, 221, 113));
        Pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PengembalianMouseClicked(evt);
            }
        });
        Pengembalian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/pengembalian.png"))); // NOI18N
        Pengembalian.add(iconPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_pengembalian.setBackground(new java.awt.Color(248, 221, 113));
        btn_pengembalian.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_pengembalian.setForeground(new java.awt.Color(0, 0, 0));
        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.setBorder(null);
        btn_pengembalian.setBorderPainted(false);
        btn_pengembalian.setContentAreaFilled(false);
        btn_pengembalian.setFocusPainted(false);
        btn_pengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
        });
        Pengembalian.add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        Pengguna.setBackground(new java.awt.Color(248, 221, 113));
        Pengguna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PenggunaMouseClicked(evt);
            }
        });
        Pengguna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/pengguna.png"))); // NOI18N
        Pengguna.add(iconPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_pengguna.setBackground(new java.awt.Color(248, 221, 113));
        btn_pengguna.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_pengguna.setForeground(new java.awt.Color(0, 0, 0));
        btn_pengguna.setText("Pengguna");
        btn_pengguna.setBorder(null);
        btn_pengguna.setBorderPainted(false);
        btn_pengguna.setContentAreaFilled(false);
        btn_pengguna.setFocusPainted(false);
        btn_pengguna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penggunaMouseClicked(evt);
            }
        });
        Pengguna.add(btn_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        Laporan.setBackground(new java.awt.Color(248, 221, 113));
        Laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanMouseClicked(evt);
            }
        });
        Laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/laporan.png"))); // NOI18N
        Laporan.add(iconLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        btn_laporan.setBackground(new java.awt.Color(248, 221, 113));
        btn_laporan.setFont(new java.awt.Font("Outfit", 0, 15)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(0, 0, 0));
        btn_laporan.setText("Laporan");
        btn_laporan.setBorder(null);
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setFocusPainted(false);
        btn_laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        Laporan.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 50));

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Kasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Sewaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Beranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        getContentPane().add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 190, 560));

        icon.setBackground(new java.awt.Color(252, 191, 73));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/logoMenu.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Outfit Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Awan Adventure");

        javax.swing.GroupLayout iconLayout = new javax.swing.GroupLayout(icon);
        icon.setLayout(iconLayout);
        iconLayout.setHorizontalGroup(
            iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        iconLayout.setVerticalGroup(
            iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 120));

        logout.setFont(new java.awt.Font("Outfit", 0, 20)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, -1, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        infoMenu.setFont(new java.awt.Font("Outfit", 1, 36)); // NOI18N
        infoMenu.setForeground(new java.awt.Color(0, 0, 0));
        infoMenu.setText("Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 550, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        infoSubmenu.setFont(new java.awt.Font("Outfit Thin", 1, 14)); // NOI18N
        infoSubmenu.setText("Submenu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(infoSubmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoSubmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 570, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/user.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, 80));

        txt_akses.setFont(new java.awt.Font("Outfit", 1, 18)); // NOI18N
        txt_akses.setForeground(new java.awt.Color(0, 0, 0));
        txt_akses.setText("Akun");
        getContentPane().add(txt_akses, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 60, 30));

        jDesktopPane1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 1010, 560));

        txt_namaUser.setFont(new java.awt.Font("Outfit Thin", 0, 14)); // NOI18N
        txt_namaUser.setText("nama");
        getContentPane().add(txt_namaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 42, 60, -1));

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Outfit Black", 0, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/close.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, -1));

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Outfit Black", 0, 24)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/minimize.png"))); // NOI18N
        minimize.setToolTipText("");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 40, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/main.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1010, 670));

        tempat_idPengguna.setText("jLabel3");
        getContentPane().add(tempat_idPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int confirmLogout = JOptionPane.showConfirmDialog(null, "Yakin ingin Logout ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(confirmLogout == JOptionPane.YES_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
            
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void KasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KasirMouseClicked
        // TODO add your handling code here:
        KasirFrame kf = new KasirFrame();
        jDesktopPane1.add(kf);
        kf.ambilId(tempat_idPengguna.getText());
        kf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new BarangFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
                
        infoMenu.setText("Form Kasir");
        infoSubmenu.setText("Home / Kasir");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(colorHover);
        Kasir.setBackground(colorHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_KasirMouseClicked

    private void btn_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kasirMouseClicked
        // TODO add your handling code here:
        KasirFrame kf = new KasirFrame();
        jDesktopPane1.add(kf);
        kf.ambilId(tempat_idPengguna.getText());
        kf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new BarangFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Form Kasir");
        infoSubmenu.setText("Home / Kasir");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(colorHover);
        Kasir.setBackground(colorHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_btn_kasirMouseClicked

    private void SewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SewaanMouseClicked
        // TODO add your handling code here:
        SewaanFrame sf = new SewaanFrame();
        jDesktopPane1.add(sf);
        sf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new BarangFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Data Sewaan");
        infoSubmenu.setText("Home / Sewaan");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(colorHover);
        Sewaan.setBackground(colorHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_SewaanMouseClicked

    private void btn_sewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sewaanMouseClicked
        // TODO add your handling code here:
        SewaanFrame sf = new SewaanFrame();
        jDesktopPane1.add(sf);
        sf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new BarangFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Data Sewaan");
        infoSubmenu.setText("Home / Sewaan");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(colorHover);
        Sewaan.setBackground(colorHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_btn_sewaanMouseClicked

    private void BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMouseClicked
        // TODO add your handling code here:
        BarangFrame bf = new BarangFrame();
        jDesktopPane1.add(bf);
        bf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Data Barang");
        infoSubmenu.setText("Home / Barang");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(colorHover);
        Barang.setBackground(colorHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_BarangMouseClicked

    private void btn_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseClicked
        // TODO add your handling code here:
        BarangFrame bf = new BarangFrame();
        jDesktopPane1.add(bf);
        bf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Data Barang");
        infoSubmenu.setText("Home / Barang");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(colorHover);
        Barang.setBackground(colorHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_btn_barangMouseClicked

    private void PengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianMouseClicked
        // TODO add your handling code here:
        PengembalianFrame pf = new PengembalianFrame();
        jDesktopPane1.add(pf);
        pf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new BarangFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Form Pengembalian");
        infoSubmenu.setText("Home / Pengembalian");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(colorHover);
        Pengembalian.setBackground(colorHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_PengembalianMouseClicked

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
        PengembalianFrame pf = new PengembalianFrame();
        jDesktopPane1.add(pf);
        pf.setVisible(true);
        
        new DashboardFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new BarangFrame().setVisible(false);
        new PenggunaFrame().setVisible(false);
        
        infoMenu.setText("Form Pengembalian");
        infoSubmenu.setText("Home / Pengembalian");
        
        btn_beranda.setBackground(exitHover);
        Beranda.setBackground(exitHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(colorHover);
        Pengembalian.setBackground(colorHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void PenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenggunaMouseClicked
        // TODO add your handling code here:
        if(txt_akses.getText().equals("Admin")){
            PenggunaFrame pf = new PenggunaFrame();
            jDesktopPane1.add(pf);
            pf.setVisible(true);

            new DashboardFrame().setVisible(false);
            new KasirFrame().setVisible(false);
            new SewaanFrame().setVisible(false);
            new PengembalianFrame().setVisible(false);
            new BarangFrame().setVisible(false);

            infoMenu.setText("Pengguna");
            infoSubmenu.setText("Home / Pengguna");

            btn_beranda.setBackground(exitHover);
            Beranda.setBackground(exitHover);
            btn_kasir.setBackground(exitHover);
            Kasir.setBackground(exitHover);
            btn_sewaan.setBackground(exitHover);
            Sewaan.setBackground(exitHover);
            btn_barang.setBackground(exitHover);
            Barang.setBackground(exitHover);
            btn_pengembalian.setBackground(exitHover);
            Pengembalian.setBackground(exitHover);
            btn_pengguna.setBackground(colorHover);
            Pengguna.setBackground(colorHover);
            btn_laporan.setBackground(exitHover);
            Laporan.setBackground(exitHover);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mohon maaf anda tidak bisa mengakses menu ini");
        }
    }//GEN-LAST:event_PenggunaMouseClicked

    private void btn_penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penggunaMouseClicked
        // TODO add your handling code here:
        if(txt_akses.getText().equals("Admin")){
            PenggunaFrame pf = new PenggunaFrame();
            jDesktopPane1.add(pf);
            pf.setVisible(true);

            new DashboardFrame().setVisible(false);
            new KasirFrame().setVisible(false);
            new SewaanFrame().setVisible(false);
            new PengembalianFrame().setVisible(false);
            new BarangFrame().setVisible(false);

            infoMenu.setText("Pengguna");
            infoSubmenu.setText("Home / Pengguna");

            btn_beranda.setBackground(exitHover);
            Beranda.setBackground(exitHover);
            btn_kasir.setBackground(exitHover);
            Kasir.setBackground(exitHover);
            btn_sewaan.setBackground(exitHover);
            Sewaan.setBackground(exitHover);
            btn_barang.setBackground(exitHover);
            Barang.setBackground(exitHover);
            btn_pengembalian.setBackground(exitHover);
            Pengembalian.setBackground(exitHover);
            btn_pengguna.setBackground(colorHover);
            Pengguna.setBackground(colorHover);
            btn_laporan.setBackground(exitHover);
            Laporan.setBackground(exitHover);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mohon maaf anda tidak bisa mengakses menu ini");
        }
        
    }//GEN-LAST:event_btn_penggunaMouseClicked

    private void LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseClicked
        // TODO add your handling code here:
        if (txt_akses.getText().equals("Admin")) {
            LaporanFrame lf = new LaporanFrame();
            jDesktopPane1.add(lf);
            lf.setVisible(true);
            infoMenu.setText("Laporan");
            infoSubmenu.setText("Home / Laporan");

            btn_beranda.setBackground(exitHover);
            Beranda.setBackground(exitHover);
            btn_kasir.setBackground(exitHover);
            Kasir.setBackground(exitHover);
            btn_sewaan.setBackground(exitHover);
            Sewaan.setBackground(exitHover);
            btn_barang.setBackground(exitHover);
            Barang.setBackground(exitHover);
            btn_pengembalian.setBackground(exitHover);
            Pengembalian.setBackground(exitHover);
            btn_pengguna.setBackground(exitHover);
            Pengguna.setBackground(exitHover);
            btn_laporan.setBackground(colorHover);
            Laporan.setBackground(colorHover);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mohon maaf anda tidak bisa mengakses menu ini");
        }     
    }//GEN-LAST:event_LaporanMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        if (txt_akses.getText().equals("Admin")) {
            LaporanFrame lf = new LaporanFrame();
            jDesktopPane1.add(lf);
            lf.setVisible(true);
            infoMenu.setText("Laporan");
            infoSubmenu.setText("Home / Laporan");

            btn_beranda.setBackground(exitHover);
            Beranda.setBackground(exitHover);
            btn_kasir.setBackground(exitHover);
            Kasir.setBackground(exitHover);
            btn_sewaan.setBackground(exitHover);
            Sewaan.setBackground(exitHover);
            btn_barang.setBackground(exitHover);
            Barang.setBackground(exitHover);
            btn_pengembalian.setBackground(exitHover);
            Pengembalian.setBackground(exitHover);
            btn_pengguna.setBackground(exitHover);
            Pengguna.setBackground(exitHover);
            btn_laporan.setBackground(colorHover);
            Laporan.setBackground(colorHover);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mohon maaf anda tidak bisa mengakses menu ini");
        }
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_berandaMouseClicked
        // TODO add your handling code here:
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);
        infoMenu.setText("Beranda");
        infoSubmenu.setText("Home / Dashboard");

        new PenggunaFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new BarangFrame().setVisible(false);

        btn_beranda.setBackground(colorHover);
        Beranda.setBackground(colorHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_btn_berandaMouseClicked

    private void BerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaMouseClicked
        // TODO add your handling code here:
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);
        infoMenu.setText("Beranda");
        infoSubmenu.setText("Home / Dashboard");

        new PenggunaFrame().setVisible(false);
        new KasirFrame().setVisible(false);
        new SewaanFrame().setVisible(false);
        new PengembalianFrame().setVisible(false);
        new BarangFrame().setVisible(false);

        btn_beranda.setBackground(colorHover);
        Beranda.setBackground(colorHover);
        btn_kasir.setBackground(exitHover);
        Kasir.setBackground(exitHover);
        btn_sewaan.setBackground(exitHover);
        Sewaan.setBackground(exitHover);
        btn_barang.setBackground(exitHover);
        Barang.setBackground(exitHover);
        btn_pengembalian.setBackground(exitHover);
        Pengembalian.setBackground(exitHover);
        btn_pengguna.setBackground(exitHover);
        Pengguna.setBackground(exitHover);
        btn_laporan.setBackground(exitHover);
        Laporan.setBackground(exitHover);
    }//GEN-LAST:event_BerandaMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        int confirmExit = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin keluar ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(confirmExit == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barang;
    private javax.swing.JPanel Beranda;
    private javax.swing.JPanel Kasir;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Pengembalian;
    private javax.swing.JPanel Pengguna;
    private javax.swing.JPanel Sewaan;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_barang;
    private javax.swing.JButton btn_beranda;
    private javax.swing.JButton btn_kasir;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_pengguna;
    private javax.swing.JButton btn_sewaan;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel icon;
    private javax.swing.JLabel iconBarang;
    private javax.swing.JLabel iconBeranda;
    private javax.swing.JLabel iconKasir;
    private javax.swing.JLabel iconLaporan;
    private javax.swing.JLabel iconPengembalian;
    private javax.swing.JLabel iconPengguna;
    private javax.swing.JLabel iconSewaan;
    private javax.swing.JLabel infoMenu;
    private javax.swing.JLabel infoSubmenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel menubar;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel tempat_idPengguna;
    private javax.swing.JLabel txt_akses;
    private javax.swing.JLabel txt_namaUser;
    // End of variables declaration//GEN-END:variables
}
