/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package subMenu.popUp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class DetailTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form Detail_Transaksi
     */
    public DetailTransaksi() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        lbl_exit1 = new javax.swing.JLabel();
        lbl_exit2 = new javax.swing.JLabel();
        lbl_exit3 = new javax.swing.JLabel();
        lbl_exit5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detail = new javax.swing.JTable();
        lbl_exit6 = new javax.swing.JLabel();
        lbl_exit7 = new javax.swing.JLabel();
        lbl_kode = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_tgl = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(252, 191, 73));

        lbl_exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/close.png"))); // NOI18N
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });

        lbl_exit1.setFont(new java.awt.Font("Outfit Medium", 0, 18)); // NOI18N
        lbl_exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit1.setText("Detail Transaksi");
        lbl_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lbl_exit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(lbl_exit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbl_exit2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit2.setText("Kode Sewaan :");
        lbl_exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit2MouseClicked(evt);
            }
        });

        lbl_exit3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit3.setText("Nama Penyewa :");
        lbl_exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit3MouseClicked(evt);
            }
        });

        lbl_exit5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit5.setText("Tanggal Penyewaan :");
        lbl_exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit5MouseClicked(evt);
            }
        });

        table_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_detail);

        lbl_exit6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exit6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit6.setText("Total :");
        lbl_exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit6MouseClicked(evt);
            }
        });

        lbl_exit7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exit7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit7.setText("10 - 03 - 2022");
        lbl_exit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit7MouseClicked(evt);
            }
        });

        lbl_kode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_kode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_kode.setText("-");
        lbl_kode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kodeMouseClicked(evt);
            }
        });

        lbl_nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nama.setText("-");
        lbl_nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_namaMouseClicked(evt);
            }
        });

        lbl_tgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tgl.setText("-");
        lbl_tgl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tglMouseClicked(evt);
            }
        });

        lbl_total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total.setText("-");
        lbl_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_totalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_exit7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_exit2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_kode)
                        .addGap(320, 320, 320))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_exit3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_nama))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_exit5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_tgl)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_exit6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total)
                        .addGap(88, 88, 88)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_exit7)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_exit5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit6)
                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void kode_sewaan(){
        try{
            
        }
        catch(Exception e){}
    }
    
    private void LoadTable(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kode Barang");
        tableModel.addColumn("Nama Barang");
        tableModel.addColumn("Jumlah");
        
        try {
            String sql = "SELECT detail_data_sewaan.id_sewaan, data_barang.nama_barang, detail_data_sewaan.jumlah\n" +
                        "FROM detail_data_sewaan\n" +
                        "INNER JOIN data_barang\n" +
                        "ON detail_data_sewaan.id_barang = data_barang.id_barang";

            Connection connect = koneksi.Connect.GetConnection();
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rs.getString("id_sewaan"),
                    rs.getString("nama_barang"),
                    rs.getString("jumlah")
                });
            }
            table_detail.setModel(tableModel);
        } catch (Exception e) {

        }
    }
    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit1MouseClicked

    private void lbl_exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit2MouseClicked

    private void lbl_exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit3MouseClicked

    private void lbl_exit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit5MouseClicked

    private void lbl_exit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit6MouseClicked

    private void lbl_exit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit7MouseClicked

    private void lbl_kodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kodeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_kodeMouseClicked

    private void lbl_namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_namaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_namaMouseClicked

    private void lbl_tglMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tglMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_tglMouseClicked

    private void lbl_totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_totalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_totalMouseClicked

    private void table_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detailMouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_table_detailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_exit1;
    private javax.swing.JLabel lbl_exit2;
    private javax.swing.JLabel lbl_exit3;
    private javax.swing.JLabel lbl_exit5;
    private javax.swing.JLabel lbl_exit6;
    private javax.swing.JLabel lbl_exit7;
    private javax.swing.JLabel lbl_kode;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_tgl;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable table_detail;
    // End of variables declaration//GEN-END:variables
}
