/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package subMenu.popUp;

/**
 *
 * @author DELL
 */
public class DetailTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form Detail_Transaksi
     */
    public DetailTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        lbl_exit1 = new javax.swing.JLabel();
        lbl_exit2 = new javax.swing.JLabel();
        lbl_exit3 = new javax.swing.JLabel();
        lbl_exit4 = new javax.swing.JLabel();
        lbl_exit5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_exit6 = new javax.swing.JLabel();
        lbl_exit7 = new javax.swing.JLabel();
        lbl_exit8 = new javax.swing.JLabel();
        lbl_exit9 = new javax.swing.JLabel();
        lbl_exit10 = new javax.swing.JLabel();
        lbl_exit11 = new javax.swing.JLabel();
        lbl_exit12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(252, 191, 73));

        lbl_exit.setFont(new java.awt.Font("Outfit Medium", 0, 18)); // NOI18N
        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });

        lbl_exit1.setFont(new java.awt.Font("Outfit Medium", 0, 18)); // NOI18N
        lbl_exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit1.setText("Detail Transaksi");
        lbl_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addComponent(lbl_exit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_exit2.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit2.setText("Kode Sewaan :");
        lbl_exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit2MouseClicked(evt);
            }
        });

        lbl_exit3.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit3.setText("Nama Penyewa :");
        lbl_exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit3MouseClicked(evt);
            }
        });

        lbl_exit4.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit4.setText("Nama Penyewa :");
        lbl_exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseClicked(evt);
            }
        });

        lbl_exit5.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit5.setText("Tanggal Penyewaan :");
        lbl_exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit5MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Outfit", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbl_exit6.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit6.setText("Total :");
        lbl_exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit6MouseClicked(evt);
            }
        });

        lbl_exit7.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit7.setText("10 - 03 - 2022");
        lbl_exit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit7MouseClicked(evt);
            }
        });

        lbl_exit8.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit8.setText("-");
        lbl_exit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit8MouseClicked(evt);
            }
        });

        lbl_exit9.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit9.setText("-");
        lbl_exit9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit9MouseClicked(evt);
            }
        });

        lbl_exit10.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit10.setText("-");
        lbl_exit10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit10MouseClicked(evt);
            }
        });

        lbl_exit11.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit11.setText("-");
        lbl_exit11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit11MouseClicked(evt);
            }
        });

        lbl_exit12.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        lbl_exit12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit12.setText("-");
        lbl_exit12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_exit2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_exit8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_exit7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_exit3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_exit9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_exit4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_exit10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_exit5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_exit11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_exit6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_exit12)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_exit7)
                    .addComponent(lbl_exit8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_exit9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit4)
                    .addComponent(lbl_exit10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit5)
                    .addComponent(lbl_exit11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exit6)
                    .addComponent(lbl_exit12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit1MouseClicked

    private void lbl_exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit2MouseClicked

    private void lbl_exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit3MouseClicked

    private void lbl_exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseClicked

    private void lbl_exit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit5MouseClicked

    private void lbl_exit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit6MouseClicked

    private void lbl_exit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit7MouseClicked

    private void lbl_exit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit8MouseClicked

    private void lbl_exit9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit9MouseClicked

    private void lbl_exit10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit10MouseClicked

    private void lbl_exit11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit11MouseClicked

    private void lbl_exit12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_exit1;
    private javax.swing.JLabel lbl_exit10;
    private javax.swing.JLabel lbl_exit11;
    private javax.swing.JLabel lbl_exit12;
    private javax.swing.JLabel lbl_exit2;
    private javax.swing.JLabel lbl_exit3;
    private javax.swing.JLabel lbl_exit4;
    private javax.swing.JLabel lbl_exit5;
    private javax.swing.JLabel lbl_exit6;
    private javax.swing.JLabel lbl_exit7;
    private javax.swing.JLabel lbl_exit8;
    private javax.swing.JLabel lbl_exit9;
    // End of variables declaration//GEN-END:variables
}
